apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: my-namespace
data:
  SPRING_DATA_MONGODB_URI: "mongodb://mongodb-headless:27017/books"

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
  namespace: my-namespace
spec:
  serviceName: "mongodb-headless"
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb
          image: mongo:latest
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongodb-data
              mountPath: /data/db
  volumeClaimTemplates:
    - metadata:
        name: mongodb-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 10Gi

---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-headless
  namespace: my-namespace
spec:
  ports:
    - port: 27017
  clusterIP: None
  selector:
    app: mongodb

---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
  namespace: my-namespace
spec:
  selector:
    app: mongodb
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-app
  namespace: my-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-boot-app
  template:
    metadata:
      labels:
        app: spring-boot-app
    spec:
      containers:
        - name: spring-boot-app
          image: lynxeen/k8s_library:latest
          ports:
            - containerPort: 8081
          env:
            - name: SPRING_DATA_MONGODB_URI
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: SPRING_DATA_MONGODB_URI

---
apiVersion: v1
kind: Service
metadata:
  name: spring-boot-service
  namespace: my-namespace
spec:
  selector:
    app: spring-boot-app
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
      nodePort: 30001
  type: NodePort
